### PR TITLE
Upgrade packages to allow usage of node v18.x missing `mkdirp` in core Node.js

### PR DESCRIPTION
**Pull request by iamladi**
Without the packages upgraded the `npm install` fails with: npm-install-fetch: ERROR: mkdirp is not a function.

Fully error log from my console:
```
npm install
.../@smodin/fast-text-language-detection install$ npm-install-fetch
│ + resource: (@smodin/fast-text-language-detection): FastText LID-176 model
│ * location: https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin
│ @ download: 131.266.198 bytes received.
│ npm-install-fetch: ERROR: mkdirp is not a function
```

### CODE REVIEW

**Comment by TinHengWan-Derek** [comment]
Please help accept this pull request.
I am having the same issue

**Comment by KevinDanikowski** [comment]
I have merged this Pr, thank you for adding this. Will need to do an update to publish it on npm tho

**Comment by iamladi** [comment]
@KevinDanikowski Can you ping us here whenever the new package is out? Thank you.

**Comment by TinHengWan-Derek** [comment]
Thanks a lot. Please help publish it.

**Comment by TinHengWan-Derek** [comment]
@KevinDanikowski any update?

**Comment by Yetispapa** [comment]
@KevinDanikowski?

**Pull request merged**
